"""Data models for OMBM."""

from dataclasses import dataclass
from datetime import datetime
from typing import Union


@dataclass
class BookmarkRecord:
    """Represents a Safari bookmark record."""
    uuid: str
    title: str  # original safari title
    url: str
    created_at: datetime


@dataclass
class ScrapeResult:
    """Result of scraping a URL for content."""
    url: str
    text: str  # cleaned body text max 10k chars
    html_title: str


@dataclass
class LLMMetadata:
    """Metadata generated by LLM for a bookmark."""
    url: str
    name: str  # semantic title
    description: str
    tokens_used: int


@dataclass
class FolderNode:
    """Represents a folder node in the bookmark hierarchy."""
    name: str
    children: list[Union['FolderNode', 'LLMMetadata']]
